### PR TITLE
Fix #86, deIndent template code before preprocessing

### LINKED ISSUE #86: "Unexpected token 'indent'" when using pug template
### Expected behavior
These two templates should work the same as each other:

```
<template lang="pug">
  .randomContentGen`
    input(v-model="randomContent",disabled)
    button(@click="randomContentGen") Generate Content!!
</template>
```

```
<template lang="pug">
.randomContentGen
    input(v-model="randomContent",disabled)`
    button(@click="randomContentGen") Generate Content!!`
</template>
```

(There is no tab/space at the beginning of the first line inside the second template, but 2 inside the first template.)

### Actual behavior
Only the second template can be complied. When using the first template, the second line of which starts with a tab(2 spaces), an exception is thrown on my console: 

``` 
�   (vue plugin) F:\rollup-vue-test\src\components\randomContentGen.vue:2:1`
    1|
  > 2|   .randomContentGen
-------^
    3|     input(v-model="randomContent",disabled)`
    4|     button(@click="randomContentGen") Generate Content!!`
    5|

unexpected token "indent"
```

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Fixes #86. This should give template preprocessor more consistent code. vue-template-compiler also deindent before preprocessing.

/ping @znck

### CODE REVIEW

File: test/expects/pug.js [hunk 1]
```diff
@@ -1,3 +1,3 @@
-var pug = { template: "<div class=\"pug__test keep-me\"><article><p>foo</p></article></div>",cssModules: {"test":"pug__test"},};
+var pug = { template: "<div class=\"pug__test keep-me\" v-if=\"true\"><article><p>foo</p></article></div><p v-else=\"v-else\">nothing</p>",cssModules: {"test":"pug__test"},};
```
Comment (HerringtonDarkholme) [inline test/expects/pug.js]: Does `v-else` correctly work here? It seems pug cannot know `v-else` is a boolean attribute but Vue compiler does not care. I'm not a pug user personally. Maybe @aleksejevski  can give a comment.

Comment (ktsn) [inline test/expects/pug.js]: I think we need specify `doctype` option for pug compiler.
https://pugjs.org/language/doctype.html#doctype-option

Comment (HerringtonDarkholme) [inline test/expects/pug.js]: Thank you! I don't know that!
