### PR TITLE
fix: Throw style compilation errors

### LINKED ISSUE #226: Show CSS/SCSS Compile Errors
Our preference is to extract CSS/SCSS to separate file, and also stop the build process on internal rollup-plugin-vue CSS/SCSS compiler errors.

**Current**
{css: true} will show errors e.g. $variable missing
{css: false} will not show errors, and 3rd party tools may (/not) pick up the errors.

**Request**
1/ Option to compile CSS/SCSS, however not output.
or
2/ Provide output option - similar to alternate rollup tools (rollup-plugin-scss).
output: function (styles, styleNodes) { ..... }

Bob

### PR DESCRIPTION
**Pull request by Nandiin**
Fixes #226.

Changes proposed in this pull request:
- forward the errors returned from `compileStyleAsync` to alert user that something has went wrong.

/ping @znck

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -209,13 +209,18 @@ export default function VuePlugin(opts: VuePluginOptions = {}): Plugin {
             ? hash(path.basename(filename) + source)
             : hash(filename + source))
         descriptors.set(filename, descriptor)
+
+        let styles = await Promise.all(
```
Comment (znck) [inline src/index.ts]: I think `styles` can be `const`.

File: src/index.ts [hunk 2]
```diff
@@ -209,13 +209,18 @@ export default function VuePlugin(opts: VuePluginOptions = {}): Plugin {
...
+          descriptor.styles.map(async style => {
+            let compiled = await compiler.compileStyleAsync(filename, scopeId, style)
```
Comment (znck) [inline src/index.ts]: `compiled` can be `const` too.

File: src/index.ts (hunk 1 above)
Comment (Nandiin) [reply src/index.ts]: Yeah, you're right.

File: src/index.ts (hunk 2 above)
Comment (Nandiin) [reply src/index.ts]: have made it 'const'
