### PR TITLE
fix: add language fallback for template code

### LINKED ISSUE #406: Babel doesn't transform/transpile template code
### Version
6.0.0-beta.10

### Reproduction link
[https://github.com/Nerixyz/vue-rollup-babel-issue](https://github.com/Nerixyz/vue-rollup-babel-issue)

### Steps to reproduce
Use `@rolup/plugin-babel` and `@babel/preset-env`. Create a component where the template contains code that's not yet supported by a browser (thus needed to be transformed). Write similar unsupported code in a JavaScript file. 

### What is expected?
Both unsupported versions should be transformed to work in the targeted browser.

### What is actually happening?
Only code in the JavaScript file will get transformed, not the template code.

---
I've seen a similar issue where the solution was to specify the extensions for the plugin, which I did, however the issue persists. I'd guess I've missed to specify some flag.

### PR DESCRIPTION
**Pull request by Nerixyz**
Fixes #406 .

Changes proposed in this pull request:
- Add language fallback ("js") for template code (so it's able to be transformed by babel).

/ping @znck

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -478,7 +478,7 @@ function getTemplateCode(
     const idQuery = `&id=${id}`
     const scopedQuery = hasScoped ? `&scoped=true` : ``
     const srcQuery = descriptor.template.src ? `&src` : ``
-    const attrsQuery = attrsToQuery(descriptor.template.attrs)
+    const attrsQuery = attrsToQuery(descriptor.template.attrs, 'js')
```
Comment (znck) [inline src/index.ts]: Add `true` as third argument to always force `.js`

**Review by znck — CHANGES_REQUESTED** [review]

**Review by znck — APPROVED** [review]
